# Generated by Django 5.0.3 on 2024-04-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_tg_id', models.CharField(max_length=255, verbose_name='TG ID клиента')),
                ('client_orders', models.TextField(verbose_name='Заказы клиента')),
                ('client_addresses', models.TextField(verbose_name='Адреса клиента')),
                ('client_time', models.DateTimeField(verbose_name='Дата вступления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_title', models.CharField(max_length=255, verbose_name='Тема рассылки')),
                ('mail_text', models.TextField(verbose_name='Текст рассылки')),
                ('mail_time', models.DateTimeField(verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
