# Generated by Django 5.0.3 on 2024-04-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_client_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_addresses',
            field=models.TextField(verbose_name='Адреса клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_orders',
            field=models.TextField(verbose_name='Заказы клиента'),
        ),
    ]
