# Generated by Django 5.0.3 on 2024-04-02 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_prod_category_product_prod_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
