# Generated by Django 5.0.3 on 2024-04-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_To_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential_buyer', models.CharField(max_length=255, verbose_name='TG ID заказчика')),
                ('items_in_cart', models.TextField(verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_products', models.TextField(verbose_name='Товары')),
                ('order_summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('order_time', models.TimeField(verbose_name='Время заказа')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('buyer_tg_id', models.CharField(max_length=255, verbose_name='TG ID заказчика')),
                ('buyer_mail', models.CharField(max_length=255, verbose_name='E-Mail заказчика')),
                ('buyer_address', models.CharField(max_length=255, verbose_name='Адрес заказчика')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
