# Generated by Django 5.0.3 on 2024-04-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='buyer_mail',
        ),
    ]
